apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vineeta-postgresql-pvc
  namespace: grupp1
  labels:
    app: vineeta-guestbook
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
